### PR TITLE
Fix sending 8-bit data

### PR DESCRIPTION
**Pull request by ggodlewski**
Resolves: https://github.com/postalsys/imapflow/issues/99

### CODE REVIEW

**Comment by andris9** [comment]
Thanks. It is more complicated than this, and I need to review how the data is converted between binary and utf8 encodings. With your fix, ImapFlow breaks for servers that have native UTF8 support (eg. Gmail).

**Comment by ggodlewski** [comment]
I just used that to create single-use-time app to move my emails to new server. So just made a simple fix.
I thought it was trivial bug. compiler does `.toString('binary')` for literals and it's messed up while converting back to buffer.

Check this place https://github.com/postalsys/imapflow/blob/master/lib/handler/imap-compiler.js#L94

**Comment by ggodlewski** [comment]
One more thing. I just checked example https://github.com/postalsys/imapflow/issues/99 against gmail server.
It doesn't work without my fix.

**Comment by andris9** [comment]
The fix breaks unicode folder name handling. The linked code can be deceiving - `"unicode string".toString("binary")` is a no-op, so the result is still `"unicode string"` not `"binary unicode string"`. The toString method applies only if the value is a Buffer.

**Pull request closed without merging**
